/*
https://projecteuler.net/problem=2
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function sumOfEvenFibonacciNumbers(maxValue)
{    
    var fibonacciSequence = [1];
    var length = fibonacciSequence.length;
    var currentValue = 2;
    var sumOfEven = 0;
    while (currentValue < maxValue)
    {
        if (currentValue % 2 == 0)
            sumOfEven += currentValue;
        fibonacciSequence.push(currentValue);
        length++;
        currentValue = fibonacciSequence[length-1] + fibonacciSequence[length-2];
    }
   return sumOfEven;
}


console.log(sumOfEvenFibonacciNumbers(4000000));      